name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore MetaTicTacToe/MetaTicTacToe.csproj
    - name: Build
      run: dotnet build MetaTicTacToe/MetaTicTacToe.csproj --no-restore
    - name: Test
      run: dotnet test MetaTicTacToe/MetaTicTacToe.csproj --no-build --verbosity normal
