name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore MetaTicTacToe.sln
      working-directory: MetaTicTacToe

    - name: Build
      run: dotnet build --no-restore
      working-directory: MetaTicTacToe

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: MetaTicTacToe

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: MetaTicTacToe
        file: MetaTicTacToe/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/metatictactoe:latest
